// app/legal/terms/page.tsx
export const metadata = { title: "Terms of Service – Lyrgenic" };

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4 space-y-8 text-foreground">
      <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">
        Last updated: {new Date().getFullYear()}
      </p>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          1. Acceptance of Terms
        </h2>
        <p>
          By accessing or using Lyrgenic (&quot;the Service&quot;), you agree to
          be bound by these Terms of Service. If you do not agree, please do not
          use the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          2. Description of Service
        </h2>
        <p>
          Lyrgenic is an AI-powered lyrics generation platform that helps
          artists create original lyrical content for their musical
          compositions. The Service uses large language models to generate lyric
          suggestions based on your inputs.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          3. AI-Generated Content &amp; Originality
        </h2>
        <p>
          <strong className="text-foreground/80">Important:</strong> Lyrics
          generated by Lyrgenic are AI-produced suggestions. While our system is
          designed to generate original content, we make no guarantee that
          generated lyrics are entirely unique or free from similarity to
          existing works. You are solely responsible for:
        </p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Reviewing generated lyrics before use or publication</li>
          <li>Ensuring compliance with applicable copyright laws</li>
          <li>Obtaining any necessary clearances before commercial use</li>
          <li>
            Not reproducing lyrics that may be protected by third-party
            copyrights
          </li>
        </ul>
        <p>
          Lyrgenic expressly disclaims any liability for copyright infringement
          arising from your use of AI-generated lyrics in your works.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          4. Your Content &amp; License
        </h2>
        <p>
          You retain ownership of any music files you upload and any edits you
          make to generated lyrics. By uploading content, you grant Lyrgenic a
          limited, non-exclusive license to process your content for the purpose
          of providing the Service.
        </p>
        <p>
          Lyrics generated by the Service are provided to you for your use. We
          do not claim ownership over AI-generated output produced in response
          to your requests.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          5. Prohibited Uses
        </h2>
        <p>You may not use the Service to generate content that is:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Hateful, harassing, or discriminatory</li>
          <li>Sexually explicit content involving minors</li>
          <li>
            Intentionally designed to infringe on third-party intellectual
            property
          </li>
          <li>Used for spam, phishing, or other malicious purposes</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          6. Free Service
        </h2>
        <p>
          Lyrgenic is currently provided free of charge with no subscription or
          payment required. We reserve the right to introduce paid features in
          the future, with advance notice to existing users.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          7. Disclaimer of Warranties
        </h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any
          kind, express or implied. We do not warrant that generated lyrics will
          be accurate, complete, or suitable for any particular purpose.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          8. Limitation of Liability
        </h2>
        <p>
          To the maximum extent permitted by law, Lyrgenic shall not be liable
          for any indirect, incidental, special, consequential, or punitive
          damages arising from your use of or inability to use the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">
          9. Changes to Terms
        </h2>
        <p>
          We reserve the right to update these Terms at any time. Continued use
          of the Service after changes constitutes your acceptance of the
          revised Terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">10. Contact</h2>
        <p>
          For questions about these Terms, please contact us at{" "}
          <a
            href="mailto:legal@lyrgenic.com"
            className="text-purple-400 hover:underline"
          >
            legal@lyrgenic.com
          </a>
          .
        </p>
      </section>
    </div>
  );
}
